### ISSUE TITLE
Maintaining code base by refactoring styles with class and/or CSS custom properties

### ISSUE THREAD

**Issue by zannain** [xiaobin900114/ColmarAcademy#3]
Avoid [combining](https://github.com/xiaobin900114/ColmarAcademy/blob/master/resources/css/style.css#L136-L149) element selectors with class or id selectors. This is generally not considered [best practice](https://google.github.io/styleguide/htmlcssguide.html#Type_Selectors) and a better alternative is to just use an `id` instead if its a unique style. 

If it's a common style you can create a specific class for that style and call it in in the HTML

```css
.pd-10 {
   padding: 10px;
}
```

```html
<div class="pd-10">
    <p>Hello World</p>
</div>
<div class="pd-10">
    <p>Bye World</p>
</div>
```

This is actually how CSS frameworks such as [Bootstrap](https://getbootstrap.com/) work!

Alternatively, you can also use [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables), these are new to CSS3 but they make it much easier to update a style found in several elements at once because you don't need to do a search for every element that has a certain style. 

```css
:root {
    --font-size: 1.75rem;
    --font-weight: bold;
}

h1 {
     font-size: var(--font-size);
}

.className {
    font-weight: var(--font-weight);
}
```
